# This file is used by .github/workflows/pr-labeler.yml to label pull requests based on the files changed in the PR.
# Object matching syntax: https://github.com/actions/labeler/blob/main/README.md#match-object

system:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
          - .github/**
          - .husky/**
          - .vscode/**
          - .*
          - front-matter-config.json

l10n-de:
  - changed-files:
      - any-glob-to-any-file:
          - files/de/**
          - docs/de/**
          - .github/ISSUE_TEMPLATE/page-report-de.yml
