name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    # do not run on PRs in forks
    if: github.repository == 'mdn/translated-content-de'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
